# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MVVMLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMLogin
  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'RxSwiftUtilities'
  #Network
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'Moya/RxSwift'
  #Layout
  pod 'SnapKit'
  
  #UI Control
  pod 'MBProgressHUD'
  
  target 'MVVMLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
